// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWyhxC-UY2UJd0_yE_WPOV4V33yMy-O0',
    appId: '1:1081580251049:web:f87a730b45b7edc71306b8',
    messagingSenderId: '1081580251049',
    projectId: 'ars-printing-press',
    authDomain: 'ars-printing-press.firebaseapp.com',
    databaseURL: 'https://ars-printing-press-default-rtdb.firebaseio.com',
    storageBucket: 'ars-printing-press.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdANMtFydVPSkTpursH--rvg0T5V8zRIs',
    appId: '1:1081580251049:android:9f436b34670940a01306b8',
    messagingSenderId: '1081580251049',
    projectId: 'ars-printing-press',
    databaseURL: 'https://ars-printing-press-default-rtdb.firebaseio.com',
    storageBucket: 'ars-printing-press.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw79ryKM8io-GLvKQWXjvbxcGxFJvmfCk',
    appId: '1:1081580251049:ios:5e6abd4061eb540d1306b8',
    messagingSenderId: '1081580251049',
    projectId: 'ars-printing-press',
    databaseURL: 'https://ars-printing-press-default-rtdb.firebaseio.com',
    storageBucket: 'ars-printing-press.appspot.com',
    iosBundleId: 'com.example.iseeyou2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw79ryKM8io-GLvKQWXjvbxcGxFJvmfCk',
    appId: '1:1081580251049:ios:5e6abd4061eb540d1306b8',
    messagingSenderId: '1081580251049',
    projectId: 'ars-printing-press',
    databaseURL: 'https://ars-printing-press-default-rtdb.firebaseio.com',
    storageBucket: 'ars-printing-press.appspot.com',
    iosBundleId: 'com.example.iseeyou2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATWyhxC-UY2UJd0_yE_WPOV4V33yMy-O0',
    appId: '1:1081580251049:web:d5bda12a7da8bab81306b8',
    messagingSenderId: '1081580251049',
    projectId: 'ars-printing-press',
    authDomain: 'ars-printing-press.firebaseapp.com',
    databaseURL: 'https://ars-printing-press-default-rtdb.firebaseio.com',
    storageBucket: 'ars-printing-press.appspot.com',
  );
}
